// GENERATED CODE - DO NOT MODIFY BY HAND

/// Which properties of the published contract accept `null`.
///
/// json_serializable describes a field by its type without its nullability, so a
/// `String?` is published as `{"type": "string"}` and an explicit `null` - which
/// `toJson` writes and `fromJson` reads - fails against it.
/// [assembleNullability] widens the ones listed here.
const nullableProperties = <String, List<String>>{
  'AboutPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background', 'mainLogo'],
  'AppBarConfig': [
    'actionsIconTheme',
    'backgroundColor',
    'centerTitle',
    'elevation',
    'foregroundColor',
    'iconTheme',
    'leadingWidth',
    'scrolledUnderElevation',
    'shadowColor',
    'surfaceTintColor',
    'systemOverlayStyle',
    'titleSpacing',
    'titleTextStyle',
    'toolbarHeight',
    'toolbarTextStyle',
  ],
  'AppConfigContactDetailsActions': ['appBar', 'emailTile', 'phoneTile'],
  'AppConfigLoginCommon': ['fullScreenLaunchEmbeddedResourceId'],
  'AppConfigLoginModeSelect': ['greetingL10n'],
  'AppConfigLoginQr': ['expectedHost'],
  'AppConfigLoginQrFormat': ['schemes'],
  'AppConfigModeSelectAction': ['embeddedId'],
  'AppConfigSettingsItem': ['embeddedResourceId', 'iconColor'],
  'AppIconWidgetConfig': ['color'],
  'BlurredSurfaceConfig': ['color', 'sigmaX', 'sigmaY'],
  'BorderConfig': ['borderColor', 'borderRadius', 'borderWidth'],
  'BorderSideConfig': ['color'],
  'BorderWidgetConfig': ['errorColor', 'typicalColor'],
  'BottomNavigationBarWidgetConfig': ['backgroundColor', 'selectedItemColor', 'unSelectedItemColor'],
  'ButtonStyleConfig': [
    'animationDuration',
    'backgroundColor',
    'disabledBackgroundColor',
    'disabledForegroundColor',
    'disabledIconColor',
    'disabledShadowColor',
    'elevation',
    'fixedSize',
    'foregroundColor',
    'iconColor',
    'iconSize',
    'maximumSize',
    'minimumSize',
    'overlayColor',
    'padding',
    'selectedBackgroundColor',
    'selectedForegroundColor',
    'selectedIconColor',
    'shadowColor',
    'shape',
    'side',
    'surfaceTintColor',
    'textStyle',
    'visualDensity',
  ],
  'ButtonWidgetConfig': ['primaryElevatedButton'],
  'CallPageActionsConfig': ['keypadInputStyle'],
  'CallPageConfig': [
    'actingOnHint',
    'actions',
    'appBarBlurredSurface',
    'appBarStyle',
    'background',
    'callInfo',
    'callList',
    'systemUiOverlayStyle',
  ],
  'CallPageHintConfig': ['affectedNameColor', 'backgroundColor'],
  'CallPageInfoConfig': ['callStatusTextStyle', 'numberTextStyle', 'processingStatusTextStyle', 'usernameTextStyle'],
  'CallPageListConfig': [
    'dotHeldColor',
    'dotOnCallColor',
    'dotRingingColor',
    'rowBackgroundColor',
    'rowFocusedBackgroundColor',
    'rowFocusedBorderColor',
  ],
  'ColorSchemeOverride': [
    'error',
    'errorContainer',
    'inversePrimary',
    'inverseSurface',
    'onError',
    'onErrorContainer',
    'onInverseSurface',
    'onPrimary',
    'onPrimaryContainer',
    'onPrimaryFixed',
    'onPrimaryFixedVariant',
    'onSecondary',
    'onSecondaryContainer',
    'onSecondaryFixed',
    'onSecondaryFixedVariant',
    'onSurface',
    'onSurfaceVariant',
    'onTertiary',
    'onTertiaryContainer',
    'onTertiaryFixed',
    'onTertiaryFixedVariant',
    'outline',
    'outlineVariant',
    'primary',
    'primaryContainer',
    'primaryFixed',
    'primaryFixedDim',
    'scrim',
    'secondary',
    'secondaryContainer',
    'secondaryFixed',
    'secondaryFixedDim',
    'shadow',
    'surface',
    'surfaceBright',
    'surfaceContainer',
    'surfaceContainerHigh',
    'surfaceContainerHighest',
    'surfaceContainerLow',
    'surfaceContainerLowest',
    'surfaceDim',
    'surfaceTint',
    'tertiary',
    'tertiaryContainer',
    'tertiaryFixed',
    'tertiaryFixedDim',
  ],
  'ConfirmDialogWidgetConfig': [
    'activeButtonColor1',
    'activeButtonColor2',
    'backgroundColor',
    'borderRadius',
    'contentTextStyle',
    'defaultButtonColor',
    'elevation',
    'surfaceTintColor',
    'titleTextStyle',
  ],
  'ContactsPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'ConversationsPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'DialogThemeConfig': [
    'backgroundColor',
    'barrierColor',
    'borderRadius',
    'contentTextStyle',
    'elevation',
    'shadowColor',
    'surfaceTintColor',
    'titleTextStyle',
  ],
  'EmbeddedPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'EmbeddedResource': ['reconnectStrategy'],
  'EncodingDefaultPresetOverride': [
    'audioBitrate',
    'maxptime',
    'opusBitrate',
    'opusDtx',
    'opusSamplingRate',
    'opusStereo',
    'ptime',
    'remapTE8payloadTo101',
    'removeExtmaps',
    'removeREMBFeedback',
    'removeStaticAudioRtpMaps',
    'removeTWCCFeedback',
    'videoBitrate',
  ],
  'EnumProperty': ['defaultValue'],
  'ExtTabBarWidgetConfig': ['backgroundColor', 'foregroundColor', 'selectedItemColor', 'unSelectedItemColor'],
  'FavoritesPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'FontsConfig': ['fontFamily'],
  'GroupTitleListTileWidgetConfig': ['backgroundColor', 'textStyle'],
  'IconThemeDataConfig': [
    'applyTextScaling',
    'color',
    'fill',
    'grade',
    'opacity',
    'opticalSize',
    'shadows',
    'size',
    'weight',
  ],
  'ImageAssetConfig': ['imageSource', 'uri'],
  'ImageAssetsConfig': ['defaultPlaceholderImage'],
  'ImageRenderSpec': ['alignment', 'fit', 'padding', 'scale'],
  'ImageSource': ['id', 'render', 'uri'],
  'InputDecorationConfig': [
    'border',
    'disabledBorder',
    'enabledBorder',
    'errorBorder',
    'errorStyle',
    'fillColor',
    'filled',
    'focusedBorder',
    'focusedErrorBorder',
    'helperStyle',
    'helperText',
    'hintStyle',
    'hintText',
    'labelStyle',
    'labelText',
    'prefixStyle',
    'prefixText',
    'suffixStyle',
    'suffixText',
  ],
  'InputValueConfig': ['includePrefixInData', 'initialValue'],
  'KeypadPageConfig': [
    'actionpad',
    'appBarBlurredSurface',
    'appBarStyle',
    'background',
    'contactName',
    'keypad',
    'systemUiOverlayStyle',
    'textField',
  ],
  'KeypadStyleConfig': ['padding', 'spacing', 'subtextStyle', 'textStyle'],
  'LeadingAvatarStyleConfig': [
    'backgroundColor',
    'initialsTextStyle',
    'loading',
    'nameColors',
    'placeholderIcon',
    'presenceBadge',
    'radius',
    'registeredBadge',
    'smartIndicator',
  ],
  'LinkifyWidgetConfig': ['linkifyStyleColor', 'styleColor'],
  'LoadingOverlayStyleConfig': ['strokeWidth'],
  'LoginCoreUrlAssignPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background', 'systemUiOverlayStyle'],
  'LoginModeSelectPageConfig': [
    'appBarBlurredSurface',
    'appBarStyle',
    'background',
    'greetingTextStyle',
    'mainLogo',
    'systemUiOverlayStyle',
  ],
  'LoginOtpSigninPageConfig': ['refTextField'],
  'LoginPasswordSigninPageConfig': ['passwordTextField', 'refTextField'],
  'LoginSwitchPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background', 'mainLogo', 'segmentButtonStyle'],
  'MaskConfig': ['filter', 'pattern'],
  'NameColorsStyleConfig': ['palette'],
  'NumberCdrsPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'OverlayStyleModel': [
    'statusBarBrightness',
    'statusBarIconBrightness',
    'systemNavigationBarColor',
    'systemNavigationBarIconBrightness',
  ],
  'PresenceBadgeStyleConfig': ['availableColor', 'busyColor', 'iconColor', 'sizeFactor', 'unavailableColor'],
  'RecentsPageConfig': ['appBarBlurredSurface', 'appBarStyle', 'background'],
  'RegisteredBadgeStyleConfig': ['registeredColor', 'sizeFactor', 'unregisteredColor'],
  'SeparatorStyleConfig': ['color'],
  'SettingsPageConfig': [
    'appBarBlurredSurface',
    'appBarStyle',
    'background',
    'groupTitleListTile',
    'itemTextStyle',
    'leadingIconsColor',
    'logoutIconColor',
    'separator',
    'userIconColor',
  ],
  'ShadowConfig': ['color', 'offset'],
  'ShapeBorderConfig': ['borderRadius'],
  'SmartIndicatorStyleConfig': ['backgroundColor', 'icon', 'sizeFactor'],
  'TabBarConfig': [
    'dividerColor',
    'dividerHeight',
    'indicatorAnimation',
    'indicatorBorder',
    'indicatorColor',
    'indicatorSize',
    'labelColor',
    'labelPadding',
    'labelStyle',
    'overlayColor',
    'splashFactory',
    'tabAlignment',
    'unselectedLabelColor',
    'unselectedLabelStyle',
  ],
  'TextDecorationConfig': ['hint', 'hintStyle', 'prefixStyle', 'prefixText'],
  'TextFieldConfig': ['decoration', 'inputValue', 'mask', 'style'],
  'TextFormFieldWidgetConfig': ['labelColor'],
  'TextSelectionWidgetConfig': ['cursorColor', 'selectionColor', 'selectionHandleColor'],
  'TextStyleConfig': [
    'backgroundBorderRadius',
    'backgroundColor',
    'backgroundPadding',
    'color',
    'decoration',
    'fontFamily',
    'fontSize',
    'fontStyle',
    'fontWeight',
    'height',
    'letterSpacing',
    'wordSpacing',
  ],
  'ThemeWidgetConfig': ['group'],
  'ToolbarConfig': ['titleL10n'],
  '_ClassInfo': ['freezedUnionKey', 'redirectsTo', 'superName'],
  '_FieldInfo': ['defaultConstant'],
  '_Property': ['defaultValue'],
};
