include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
  errors:
    deprecated_subclass: ignore
    
formatter:
  page_width: 120
