// Autogenerated from Pigeon (v26.3.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.webtrit.signaling_service

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Mirrors [SignalingServiceMode] from the platform_interface package. */
enum class PSignalingServiceMode(val raw: Int) {
  PERSISTENT(0),
  PUSH_BOUND(1);

  companion object {
    fun ofRaw(raw: Int): PSignalingServiceMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PSignalingServiceStatus (
  val enabled: Boolean,
  val coreUrl: String,
  val tenantId: String,
  val token: String,
  /**
   * JSON-encoded list of trusted certificate entries, each with 'bytes' (List<int>)
   * and optional 'password' (String). Null when the app uses the default system trust store.
   *
   * Persisted via [PSignalingServiceHostApi.saveTrustedCertificates] so that
   * the background isolate can reconstruct [TrustedCertificates] without access
   * to the main-isolate DI context.
   */
  val trustedCertificatesJson: String? = null,
  /**
   * Raw handle for the app-side incoming call callback.
   *
   * Obtained via [PluginUtilities.getCallbackHandle] in the main isolate and
   * persisted via [PSignalingServiceHostApi.saveIncomingCallHandler].
   * 0 means no handler is registered.
   */
  val incomingCallHandlerHandle: Long,
  /**
   * Raw handle for the app-side [SignalingModuleFactory] callback.
   *
   * Obtained via [PluginUtilities.getCallbackHandle] and persisted via
   * [PSignalingServiceHostApi.saveModuleFactory]. 0 means no factory registered.
   */
  val moduleFactoryHandle: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PSignalingServiceStatus {
      val enabled = pigeonVar_list[0] as Boolean
      val coreUrl = pigeonVar_list[1] as String
      val tenantId = pigeonVar_list[2] as String
      val token = pigeonVar_list[3] as String
      val trustedCertificatesJson = pigeonVar_list[4] as String?
      val incomingCallHandlerHandle = pigeonVar_list[5] as Long
      val moduleFactoryHandle = pigeonVar_list[6] as Long
      return PSignalingServiceStatus(enabled, coreUrl, tenantId, token, trustedCertificatesJson, incomingCallHandlerHandle, moduleFactoryHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      coreUrl,
      tenantId,
      token,
      trustedCertificatesJson,
      incomingCallHandlerHandle,
      moduleFactoryHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PSignalingServiceStatus
    return MessagesPigeonUtils.deepEquals(this.enabled, other.enabled) && MessagesPigeonUtils.deepEquals(this.coreUrl, other.coreUrl) && MessagesPigeonUtils.deepEquals(this.tenantId, other.tenantId) && MessagesPigeonUtils.deepEquals(this.token, other.token) && MessagesPigeonUtils.deepEquals(this.trustedCertificatesJson, other.trustedCertificatesJson) && MessagesPigeonUtils.deepEquals(this.incomingCallHandlerHandle, other.incomingCallHandlerHandle) && MessagesPigeonUtils.deepEquals(this.moduleFactoryHandle, other.moduleFactoryHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enabled)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.coreUrl)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tenantId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.token)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.trustedCertificatesJson)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.incomingCallHandlerHandle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.moduleFactoryHandle)
    return result
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PSignalingServiceMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PSignalingServiceStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PSignalingServiceMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PSignalingServiceStatus -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PSignalingServiceHostApi {
  /**
   * Register the Dart callback dispatcher handle and the onSync entry point handle.
   * Must be called before [startService].
   */
  fun initializeServiceCallback(callbackDispatcher: Long, onSync: Long)
  /**
   * Persist connection credentials so the foreground service can deliver them
   * to the background isolate via [PSignalingServiceFlutterApi.onSynchronize].
   * Must be called before [startService].
   */
  fun saveConnectionConfig(coreUrl: String, tenantId: String, token: String)
  /**
   * Persist JSON-encoded trusted certificates for the background isolate.
   *
   * Pass null to clear (revert to system trust store). Call before [startService]
   * so the isolate receives the correct TLS configuration on first sync.
   */
  fun saveTrustedCertificates(certificatesJson: String?)
  /**
   * Persist the raw callback handle for the app-side incoming call handler.
   *
   * The handle is obtained via [PluginUtilities.getCallbackHandle] on a
   * top-level function annotated with [@pragma('vm:entry-point')].
   * Pass 0 to unregister.
   */
  fun saveIncomingCallHandler(callbackHandle: Long)
  /**
   * Persist the raw callback handle for the app-side [SignalingModuleFactory].
   *
   * The handle is obtained via [PluginUtilities.getCallbackHandle] on a
   * top-level function annotated with [@pragma('vm:entry-point')].
   */
  fun saveModuleFactory(callbackHandle: Long)
  /** Set the foreground service notification text. */
  fun configureService(notificationTitle: String, notificationDescription: String)
  /**
   * Start the foreground service (idempotent).
   *
   * [mode] controls whether the service stops when the app Activity is closed
   * ([PSignalingServiceMode.pushBound]) or runs indefinitely
   * ([PSignalingServiceMode.persistent]).
   */
  fun startService(mode: PSignalingServiceMode)
  /** Stop the foreground service. */
  fun stopService()
  /**
   * Called from the background Dart isolate after [PSignalingServiceFlutterApi.setUp]
   * completes, signalling that the isolate is ready to receive [onSynchronize] calls.
   *
   * Kotlin responds by calling [SignalingForegroundService.synchronizeIsolate] so
   * the service delivers the current status to the freshly-initialised isolate.
   */
  fun notifyIsolateReady()

  companion object {
    /** The codec used by PSignalingServiceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PSignalingServiceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PSignalingServiceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.initializeServiceCallback$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val callbackDispatcherArg = args[0] as Long
            val onSyncArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.initializeServiceCallback(callbackDispatcherArg, onSyncArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.saveConnectionConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val coreUrlArg = args[0] as String
            val tenantIdArg = args[1] as String
            val tokenArg = args[2] as String
            val wrapped: List<Any?> = try {
              api.saveConnectionConfig(coreUrlArg, tenantIdArg, tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.saveTrustedCertificates$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val certificatesJsonArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.saveTrustedCertificates(certificatesJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.saveIncomingCallHandler$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val callbackHandleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.saveIncomingCallHandler(callbackHandleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.saveModuleFactory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val callbackHandleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.saveModuleFactory(callbackHandleArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.configureService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val notificationTitleArg = args[0] as String
            val notificationDescriptionArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.configureService(notificationTitleArg, notificationDescriptionArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.startService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as PSignalingServiceMode
            val wrapped: List<Any?> = try {
              api.startService(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.stopService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopService()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceHostApi.notifyIsolateReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.notifyIsolateReady()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PSignalingServiceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PSignalingServiceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /**
   * Called by Kotlin when the Flutter engine is ready and the current
   * service status should be replayed to the freshly-started isolate.
   */
  fun onSynchronize(statusArg: PSignalingServiceStatus, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.webtrit_signaling_service_android.PSignalingServiceFlutterApi.onSynchronize$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(statusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
