include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true

formatter:
  page_width: 120
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
