name: webtrit_theme
description: Webtrit phone theming module.
version: 0.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed: ^2.3.4
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
