// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe8pkZdFusbdWZqWQlv533x-welRG1pOw',
    appId: '1:973049735976:web:8cd789c0e89ea49b547e1d',
    messagingSenderId: '973049735976',
    projectId: 'webtrit-app',
    authDomain: 'webtrit-app.firebaseapp.com',
    storageBucket: 'webtrit-app.appspot.com',
    measurementId: 'G-NNFJ03JQDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq1cn3u6oeWVHTdAAhwdsy78tRpb4ab2Y',
    appId: '1:973049735976:android:3b8774082803ad8f547e1d',
    messagingSenderId: '973049735976',
    projectId: 'webtrit-app',
    storageBucket: 'webtrit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDRXt-svULnPAy7K_sMgC0tGB3Tj_PNFc',
    appId: '1:973049735976:ios:c8fdad3d4a4bc81a547e1d',
    messagingSenderId: '973049735976',
    projectId: 'webtrit-app',
    storageBucket: 'webtrit-app.appspot.com',
    iosClientId: '973049735976-t0te56rlsu1putg89pt2b8c4qq8f80c1.apps.googleusercontent.com',
    iosBundleId: 'com.webtrit.app',
  );
}
