// Aggregates the license text of every third-party package bundled with the app
// into THIRD_PARTY_LICENSES.md at the repository root.
//
// Source of truth is the resolved dependency set in .dart_tool/package_config.json
// (produced by `flutter pub get`), so run `flutter pub get` first. Only packages
// resolved from the pub cache (hosted or git) are included; first-party workspace
// packages and the Flutter/Dart SDK are skipped.
//
// Usage: dart run tool/generate_licenses.dart [--strict]
//   --strict: exit non-zero if any included package has no detectable LICENSE
//             file (used by CI so a new dependency cannot ship unattributed).
// Or via melos: `melos run licenses:generate`.

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

const _outputFile = 'THIRD_PARTY_LICENSES.md';
const _licenseFileNames = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENSE.markdown', 'COPYING'];

void main(List<String> args) {
  final strict = args.contains('--strict');
  final configFile = File('.dart_tool/package_config.json');
  if (!configFile.existsSync()) {
    stderr.writeln('${configFile.path} not found. Run "flutter pub get" first.');
    exit(1);
  }

  final config = jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  final packages = (config['packages'] as List).cast<Map<String, dynamic>>();

  final entries = <_Package>[];
  final missing = <String>[];

  for (final package in packages) {
    final name = package['name'] as String;
    final rootUri = package['rootUri'] as String;

    // Local/workspace packages use a relative rootUri; only absolute file URIs
    // resolved from the pub cache are third-party. Detect the cache layout via
    // URI path segments (always '/'-separated) so this stays cross-platform.
    if (!rootUri.startsWith('file://')) continue;
    final uri = Uri.parse(rootUri);
    if (!uri.pathSegments.contains('hosted') && !uri.pathSegments.contains('git')) continue;
    final root = uri.toFilePath();

    final license = _readLicense(root);
    if (license == null) {
      missing.add(name);
      continue;
    }
    entries.add(_Package(name, _versionFromPath(root, name), license));
  }

  // Deterministic order keeps the generated file stable for the CI drift check.
  entries.sort((a, b) => a.name.compareTo(b.name));

  final buffer = StringBuffer()
    ..writeln('# Third-party licenses')
    ..writeln()
    ..writeln('Generated by `tool/generate_licenses.dart` (`melos run licenses:generate`).')
    ..writeln('Do not edit by hand; regenerate after changing dependencies.')
    ..writeln()
    ..writeln('Aggregates the license text of every third-party package bundled with the')
    ..writeln('app, as resolved by `flutter pub get` (.dart_tool/package_config.json).')
    ..writeln('Total packages: ${entries.length}.')
    ..writeln();

  for (final entry in entries) {
    final heading = entry.version == null ? entry.name : '${entry.name} ${entry.version}';
    final license = entry.license.trimRight();
    // Use a fence longer than any backtick run inside the license text so a
    // license that itself contains a code fence cannot break the markdown.
    final fence = '`' * _fenceLength(license);
    buffer
      ..writeln('## $heading')
      ..writeln()
      ..writeln('${fence}text')
      ..writeln(license)
      ..writeln(fence)
      ..writeln();
  }

  File(_outputFile).writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote $_outputFile (${entries.length} packages).');
  if (missing.isNotEmpty) {
    missing.sort();
    final message = 'no LICENSE file found for ${missing.length} package(s): ${missing.join(', ')}';
    if (strict) {
      stderr.writeln('Error: $message');
      exit(1);
    }
    stdout.writeln('Warning: $message');
  }
}

/// Number of backticks for a fence that safely wraps [text]: at least 3, and
/// always one more than the longest run of backticks the text contains.
int _fenceLength(String text) {
  var longest = 0;
  var current = 0;
  for (final unit in text.codeUnits) {
    if (unit == 0x60) {
      current++;
      if (current > longest) longest = current;
    } else {
      current = 0;
    }
  }
  return longest + 1 < 3 ? 3 : longest + 1;
}

String? _readLicense(String packageRoot) {
  for (final fileName in _licenseFileNames) {
    final file = File(p.join(packageRoot, fileName));
    if (file.existsSync()) {
      // Reproduce the license verbatim; only trim for the emptiness check.
      final text = file.readAsStringSync();
      if (text.trim().isNotEmpty) return text;
    }
  }
  return null;
}

String? _versionFromPath(String packageRoot, String name) {
  final segment = p.basename(packageRoot);
  final prefix = '$name-';
  if (segment.startsWith(prefix)) return segment.substring(prefix.length);
  return null;
}

class _Package {
  _Package(this.name, this.version, this.license);

  final String name;
  final String? version;
  final String license;
}
