import 'dart:async';

import 'package:webtrit_callkeep/webtrit_callkeep.dart';

/// Root sealed hierarchy for all events that [PlatformBridge] emits onto its
/// [PlatformBridge.events] stream.
///
/// [CallBloc] subscribes to this stream and maps each event to an internal
/// BLoC event (or an inline state update).
sealed class PlatformEvent {}

// ---------------------------------------------------------------------------
// Intent events — no completion future needed
// ---------------------------------------------------------------------------

/// Emitted when the native side asks to start a call (e.g. from recents).
///
/// The [CallBloc] subscriber waits for the signaling layer to be ready before
/// forwarding this as a [CallControlEvent.started].
final class StartCallIntentPlatformEvent extends PlatformEvent {
  StartCallIntentPlatformEvent({required this.handle, this.displayName, required this.video});

  final CallkeepHandle handle;
  final String? displayName;
  final bool video;
}

/// Emitted when a push notification triggers an incoming call.
final class PushIncomingCallPlatformEvent extends PlatformEvent {
  PushIncomingCallPlatformEvent({
    required this.callId,
    required this.handle,
    this.displayName,
    required this.video,
    this.error,
  });

  final String callId;
  final CallkeepHandle handle;
  final String? displayName;
  final bool video;
  final CallkeepIncomingCallError? error;
}

// ---------------------------------------------------------------------------
// Perform events — each carries a [Completer<bool>] so that the native
// CallKit/ConnectionService layer can await the [Future<bool>] result.
// ---------------------------------------------------------------------------

/// Base class for events generated by [CallkeepDelegate]'s `perform*` callbacks.
///
/// Each instance owns a [Completer<bool>]. The [result] future is returned to
/// the native side by [PlatformBridgeImpl]. The [CallBloc] subscriber creates a
/// matching `_CallPerformEvent`, processes it, and calls [complete] to
/// propagate the outcome back to the native side.
sealed class PerformCallEvent extends PlatformEvent {
  PerformCallEvent() : _completer = Completer<bool>();

  final Completer<bool> _completer;

  /// The future the native side awaits for the outcome.
  Future<bool> get result => _completer.future;

  /// Marks the perform as successful. Idempotent.
  void complete(bool value) {
    if (!_completer.isCompleted) _completer.complete(value);
  }
}

final class StartCallPerformEvent extends PerformCallEvent {
  StartCallPerformEvent({required this.callId, required this.handle, this.displayName, required this.video});

  final String callId;
  final CallkeepHandle handle;
  final String? displayName;
  final bool video;
}

final class AnswerCallPerformEvent extends PerformCallEvent {
  AnswerCallPerformEvent(this.callId);

  final String callId;
}

final class EndCallPerformEvent extends PerformCallEvent {
  EndCallPerformEvent(this.callId);

  final String callId;
}

final class SetHeldPerformEvent extends PerformCallEvent {
  SetHeldPerformEvent(this.callId, this.onHold);

  final String callId;
  final bool onHold;
}

final class SetMutedPerformEvent extends PerformCallEvent {
  SetMutedPerformEvent(this.callId, this.muted);

  final String callId;
  final bool muted;
}

final class SendDtmfPerformEvent extends PerformCallEvent {
  SendDtmfPerformEvent(this.callId, this.key);

  final String callId;
  final String key;
}

final class AudioDeviceSetPerformEvent extends PerformCallEvent {
  AudioDeviceSetPerformEvent(this.callId, this.device);

  final String callId;
  final CallkeepAudioDevice device;
}

final class AudioDevicesUpdatePerformEvent extends PerformCallEvent {
  AudioDevicesUpdatePerformEvent(this.callId, this.devices);

  final String callId;
  final List<CallkeepAudioDevice> devices;
}
