default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    keychain_name = 'ios-build.keychain'
    keychain_password = SecureRandom.uuid

    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: ENV['IOS_CERTIFICATE_PATH'], 
      keychain_name: keychain_name,
      keychain_password: keychain_password,
    )

    install_provisioning_profile(path: ENV['IOS_PROVISIONING_PROFILE_PATH'])

    increment_build_number(
      build_number: ENV['IOS_BUILD_NUMBER'],
      xcodeproj: "Runner.xcodeproj"
    )

    increment_version_number(
      version_number: ENV['IOS_BUILD_NAME'],
      xcodeproj: "Runner.xcodeproj"
    )

    update_code_signing_settings(
      # Replaces code_sign_style_script.rb from build_tools
      use_automatic_signing: false,
      code_sign_identity: ENV['IOS_CODE_SIGNING_IDENTITY']
    )

    update_project_team(
      teamid: ENV['IOS_TEAM_ID'],
    )

    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: ENV['IOS_PROVISIONING_PROFILE_PATH'],
      target_filter: nil
    )

    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      # archive_path: "build.xcarchive", # Uncomment if you want to keep the archive, for manual upload
      output_name: ENV['IOS_BUILD_FILE_NAME'],
      export_team_id: ENV['IOS_TEAM_ID'],
      export_options: {
        signingCertificate: ENV['IOS_CODE_SIGNING_IDENTITY'],
      },
      sdk: ENV['IOS_BUILD_SDK'].nil? ? nil : ENV['IOS_BUILD_SDK'],
    )

    delete_keychain(name: keychain_name)
  end

  desc "Upload the iOS app to TestFlight"
  lane :upload do

    api_key = app_store_connect_api_key(
      key_id: ENV['IOS_APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['IOS_APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_filepath: ENV['IOS_APP_STORE_CONNECT_API_KEY_P8_PATH'],
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ENV['IOS_BUILD_FILE_NAME'],
      skip_waiting_for_build_processing: true, # Remove if need to specify test groups

      # TODO: automate testgroups
      # testers_file_path: "testers.csv",
    )
  end
end
