include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  errors:
    depend_on_referenced_packages: ignore

  exclude:
    - "**/*.g.dart"
    - "build/**"
